### ISSUE TITLE
Error: ENOENT, no such file or directory '<path>/plugins/ios.json' when trying to add a platform

### ISSUE THREAD

**Issue by qpwr** [evothings/evothings-viewer#16]
I'm trying to build my own version of the viewer app with custom plugins. I downloaded the latest release and tried to add android/ios as platforms, but I receive the error mentioned on the title. This is the full error log:

qbook:EvothingsViewer qpwr [master]$ cordova platform add ios
Creating ios project...
Error: ENOENT, no such file or directory '/Users/qpwr/CordovaApps/EvothingsViewer/plugins/ios.json'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.writeFileSync (fs.js:977:15)
    at Object.save_platform_json (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:476:8)
    at PlatformMunger_process [as process] (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:401:13)
    at Object.exports.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:80:12)
    at Object.handlePrepare (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/prepare.js:72:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:102:25
    at Array.map (native)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/prepare.js:66:40
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:798:54)

**Comment by mrcbnsls** [comment]
Any news on this issue?

**Comment by gparuthi** [comment]
You can get around this issue by adding android platform first.

**Comment by hervethouzard** [comment]
Hello,

Same problem for me.
Adding Android did not solved the problem.
