### ISSUE TITLE
Android build fail

### ISSUE THREAD

**Issue by storm1er** [evothings/evothings-viewer#28]
Hi everyone

I already build my apps multiple time. It's the first time i have this issue.
Debug uncheck

```shell
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
stderr: 
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/2.13/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
OpenJDK Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (safepoint.cpp:310), pid=1977, tid=1715682112
#  guarantee(PageArmed == 0) failed: invariant
#
# JRE version: OpenJDK Runtime Environment (8.0_91-b14) (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
# Java VM: OpenJDK Server VM (25.91-b14 mixed mode linux-x86 )
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/vagrant/.gradle/daemon/2.13/hs_err_pid1977.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
stderr: Error: /vagrant/result/323rpi/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/2.13/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
OpenJDK Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (safepoint.cpp:310), pid=1977, tid=1715682112
#  guarantee(PageArmed == 0) failed: invariant
#
# JRE version: OpenJDK Runtime Environment (8.0_91-b14) (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
# Java VM: OpenJDK Server VM (25.91-b14 mixed mode linux-x86 )
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/vagrant/.gradle/daemon/2.13/hs_err_pid1977.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
stderr: build.rb:237:in `sh': Command failed (RuntimeError)
	from build.rb:160:in `runCordova'
	from build.rb:258:in `
'
```

**Comment by storm1er** [comment]
Same problem on debug build.

Finally a quit evothings, delete build/linux32 folder, restart evothings, and it was working again.

Still don't know why it happens.
