### ISSUE TITLE
iBeacon plugin crashes app on reload

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-viewer#4]
Problem:

When reloading/rerunning the iBeacon Scan example app on an Android device, the app stops.

The following exception is shown in logcat:

	E/AndroidRuntime(14044): FATAL EXCEPTION: main
	E/AndroidRuntime(14044): Process: com.evothings.evothingsviewer, PID: 14044
	E/AndroidRuntime(14044): java.lang.NullPointerException
	E/AndroidRuntime(14044): 	at com.radiusnetworks.ibeacon.Region.equals(Region.java:151)
	E/AndroidRuntime(14044): 	at java.util.HashMap.containsKey(HashMap.java:340)
	E/AndroidRuntime(14044): 	at com.radiusnetworks.ibeacon.service.IBeaconService.startRangingBeaconsInRegion(IBeaconService.java:252)
	E/AndroidRuntime(14044): 	at com.radiusnetworks.ibeacon.service.IBeaconService$IncomingHandler.handleMessage(IBeaconService.java:145)
	E/AndroidRuntime(14044): 	at android.os.Handler.dispatchMessage(Handler.java:102)
	E/AndroidRuntime(14044): 	at android.os.Looper.loop(Looper.java:136)
	E/AndroidRuntime(14044): 	at android.app.ActivityThread.main(ActivityThread.java:5118)
	E/AndroidRuntime(14044): 	at java.lang.reflect.Method.invokeNative(Native Method)
	E/AndroidRuntime(14044): 	at java.lang.reflect.Method.invoke(Method.java:515)
	E/AndroidRuntime(14044): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
	E/AndroidRuntime(14044): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
	E/AndroidRuntime(14044): 	at dalvik.system.NativeStart.main(Native Method)
	W/ActivityManager(  959):   Force finishing activity com.evothings.evothingsviewer/.MainActivity
	V/ActivityManager(  959): Moving to PAUSING: ActivityRecord{423fd170 u0 com.evothings.evothingsviewer/.MainActivity t1154 f}

**Comment by mikaelkindborg** [comment]
Investigate if this error still happens? (The iBeacon plugin has been updated, so this may have been fixed bu the update.)

**Comment by mikaelkindborg** [comment]
Tried to reproduce with recent Viewer, error seems to be resolved in current iBeacon plugin. Closing issue.
